# Generated by Django 3.0.6 on 2023-06-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0015_auto_20230525_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(related_name='_friend_friends_+', to='socialmediaapp.Friend'),
        ),
    ]
