# Generated by Django 3.0.6 on 2023-06-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0028_auto_20230612_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='status',
        ),
    ]
