# Generated by Django 3.0.6 on 2023-06-21 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0035_auto_20230614_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='friends',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
